project: LiveClock.xcworkspace
retain_objc_accessible: true
retain_public: true
schemes:
- LiveClock-Workspace
- LiveClock-iOS
- LiveClock-macOS
- LiveClock-visionOS
- LiveClockTests-iOS
- LiveClockTests-macOS
- LiveClockTests-visionOS
