name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Build and Test (iOS)
      run: |
        xcodebuild test \
          -scheme LiveClock-iOS \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -derivedDataPath .build \
          clean test
    
    - name: Build and Test (macOS)
      run: |
        xcodebuild test \
          -scheme LiveClock-macOS \
          -destination 'platform=macOS' \
          -derivedDataPath .build \
          clean test
    
    - name: Run Swift Tests
      run: swift test

  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [iOS, macOS]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Build ${{ matrix.platform }}
      run: |
        if [ "${{ matrix.platform }}" = "iOS" ]; then
          xcodebuild build \
            -scheme LiveClock-iOS \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            clean build
        else
          xcodebuild build \
            -scheme LiveClock-macOS \
            -destination 'platform=macOS' \
            -derivedDataPath .build \
            clean build
        fi