name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    name: Test ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - platform: iOS
            scheme: LiveClock-iOS
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.5'
          - platform: macOS
            scheme: LiveClock-macOS
            destination: 'platform=macOS'
          - platform: visionOS
            scheme: LiveClock-visionOS
            destination: 'platform=visionOS Simulator,name=Apple Vision Pro'

    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Generate Xcode project and workspace
        run: tuist generate --no-open

      - name: Build and Test (${{ matrix.platform }})
        run: |
          xcodebuild test \
            -scheme ${{ matrix.scheme }} \
            -destination '${{ matrix.destination }}' \
            -derivedDataPath .build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            clean test

      - name: Archive snapshots (${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-snapshots-${{ matrix.platform }}
          path: "**/__Snapshots__/**/*.latest.png"

  test-swift:
    name: Swift Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Run Swift Tests
        run: swift test

  lint:
    name: SwiftLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  build:
    name: Build ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - platform: iOS
            scheme: LiveClock-iOS
            destination: 'generic/platform=iOS Simulator'
          - platform: macOS
            scheme: LiveClock-macOS
            destination: 'platform=macOS'
          - platform: visionOS
            scheme: LiveClock-visionOS
            destination: 'generic/platform=visionOS Simulator'

    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Generate Xcode project and workspace
        run: tuist generate --no-open

      - name: Build ${{ matrix.platform }}
        run: |
          xcodebuild build \
            -scheme ${{ matrix.scheme }} \
            -destination '${{ matrix.destination }}' \
            -derivedDataPath .build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            clean build